name: Java Maven Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'  # Commonly used distributions are 'temurin', 'adopt', or 'zulu'

    - name: Install Maven
      run: sudo apt-get install -y maven

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./java-selenium/sauce-demo-automation

    - name: Run Tests
      run: mvn test -Dheadless=true
      working-directory: ./java-selenium/sauce-demo-automation

    - name: Upload Test Results
      if: always()  # Ensures this step runs even if previous steps fail
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          ./java-selenium/sauce-demo-automation/target/surefire-reports/*.xml
          ./java-selenium/sauce-demo-automation/target/surefire-reports/*.txt
          ./java-selenium/sauce-demo-automation/target/surefire-reports/*.html
