name: Java Selenium Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  setup-environment:
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        #cache: 'maven'

  build:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
    - name: Build with Maven
      run: mvn clean install
      working-directory: java-selenium/sauce-demo-automation

  run-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run Selenium Tests
      run: mvn test
      working-directory: java-selenium/sauce-demo-automation

    - name: Upload Test Results
      if: always()  # Ensures the step runs even if the previous steps fail
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          java-selenium/sauce-demo-automation/target/surefire-reports/*.xml
          java-selenium/sauce-demo-automation/target/surefire-reports/*.txt
          java-selenium/sauce-demo-automation/target/surefire-reports/*.html
