name: Java Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install
      working-directory: java-selenium/sauce-demo-automation

    - name: Run Selenium Tests
      run: mvn test
      working-directory: java-selenium/sauce-demo-automation
